PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_FILM` (
	`UIDFILM` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`NAME` text NOT NULL,
	`ISO` integer NOT NULL,
	`EXPOSURES` integer NOT NULL,
	`STATUS` text NOT NULL,
	`EXPIRATION` integer,
	`DEVELOPEDAT` integer
);
--> statement-breakpoint
INSERT INTO `__new_FILM`("UIDFILM", "NAME", "ISO", "EXPOSURES", "STATUS", "EXPIRATION", "DEVELOPEDAT") SELECT "UIDFILM", "NAME", "ISO", "EXPOSURES", "STATUS", "EXPIRATION", "DEVELOPEDAT" FROM `FILM`;--> statement-breakpoint
DROP TABLE `FILM`;--> statement-breakpoint
ALTER TABLE `__new_FILM` RENAME TO `FILM`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE TABLE `__new_FILMLOG` (
	`UIDLOG` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`SHUTTERSPEED` integer NOT NULL,
	`APERTURE` real NOT NULL,
	`NOTES` text,
	`TIMESTAMP` integer,
	`DIGITALPHOTO` blob,
	`FILMPHOTO` blob,
	`UIDLENS` integer NOT NULL,
	`UIDFILMSESSION` integer NOT NULL,
	FOREIGN KEY (`UIDLENS`) REFERENCES `LENS`(`UIDLENS`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`UIDFILMSESSION`) REFERENCES `FILMSESSION`(`UIDFILMSESSION`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_FILMLOG`("UIDLOG", "SHUTTERSPEED", "APERTURE", "NOTES", "TIMESTAMP", "DIGITALPHOTO", "FILMPHOTO", "UIDLENS", "UIDFILMSESSION") SELECT "UIDLOG", "SHUTTERSPEED", "APERTURE", "NOTES", "TIMESTAMP", "DIGITALPHOTO", "FILMPHOTO", "UIDLENS", "UIDFILMSESSION" FROM `FILMLOG`;--> statement-breakpoint
DROP TABLE `FILMLOG`;--> statement-breakpoint
ALTER TABLE `__new_FILMLOG` RENAME TO `FILMLOG`;